/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.jupiter.api.Test;

import java.io.IOException;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    // test author return from our JSON file
    @Test void authorTest() throws IOException {
        String path ="C:\\Users\\yousef\\Desktop\\software development\\401 Java\\quotes\\app\\src\\main\\java\\quotes\\recentquotes.json";
        DeserializeQuote deserializeQuote = new DeserializeQuote();
        assertNotNull(deserializeQuote.Deserialize(path)[0].author, "Marilyn Monroe");
    }
    // test quote return from our JSON file
    @Test void quoteTest() throws IOException {
        String path ="C:\\Users\\yousef\\Desktop\\software development\\401 Java\\quotes\\app\\src\\main\\java\\quotes\\recentquotes.json";
        DeserializeQuote deserializeQuote = new DeserializeQuote();
        assertNotNull(deserializeQuote.Deserialize(path)[1].text, "�Ask no questions, and you'll be told no lies.�");
    }


}
