/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import com.google.gson.stream.JsonReader;

import java.io.*;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;

public class App {

    public static void main(String[] args) throws IOException {

        DeserializeQuote deserializeQuote = new DeserializeQuote();
        deserializeQuote.Deserialize("C:\\Users\\yousef\\Desktop\\software development\\401 Java\\quotes\\app\\src\\main\\java\\quotes\\recentquotes.json");
    }

}
