/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import java.io.*;

public class App {

    public static void main(String[] args) throws IOException {
        boolean success = false;
        try{
            QuoteAPI quoteAPI = new QuoteAPI();
            quoteAPI.readApi();
            success = true;
        }catch (Exception e){
            System.out.println("Something went wrong with API");
        }
        if (!success){
            DeserializeQuote deserializeQuote = new DeserializeQuote();
            deserializeQuote.Deserialize();
        }



    }

}
